/*
 * File: app/view/contact/Grid.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtMVC.view.contact.Grid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.contactgrid',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    iconCls: 'icon-grid',
    title: 'Contacts',
    store: 'Contacts',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 170,
                    dataIndex: 'name',
                    text: 'NAME',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    width: 160,
                    dataIndex: 'phone',
                    text: 'PHONE #',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    width: 170,
                    dataIndex: 'email',
                    text: 'EMAIL',
                    flex: 1
                }
            ],
            viewConfig: {
                emptyText: 'no contacts found'
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'top',
                    width: 360,
                    displayInfo: true,
                    emptyMsg: 'No contacts to display',
                    store: 'Contacts'
                }
            ]
        });

        me.callParent(arguments);
    }

});