/*
 * File: app/controller/Contact.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtMVC.controller.Contact', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "contactlist": {
                itemtap: 'onListItemTap'
            },
            "button#back": {
                tap: 'onButtonTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var panel = dataview.up('contactnavigation');

        panel.setActiveItem(1);

        panel.down('contactdetails').setRecord(record);
    },

    onButtonTap: function(button, e, eOpts) {
        button.up('contactnavigation').setActiveItem(0);
    }

});